name: Docker_Container_Run

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  ACCESS_TOKEN: ${{secrets.github_token}}  

jobs:
  start_runner:
    runs-on: ubuntu-latest
    container:
      image: vcolovic/github-runner:latest
    steps:  
    - name: start container
      run: docker run vcolovic/github-runner:latest