name: DockerRunner2

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
    start_runner:
      runs-on: ubuntu-latest

      steps:  
      - name: Get
        run: echo "${{secrets.GITHUB_TOKEN}}"
      - name: start container
        run: docker run --env ACCESS_TOKEN=685f984ee6af1bc05f58529f42c6e1b1ef7b5fed --env REPO=https://github.com/${{github.repository}} vcolovic/github-runner:latest 