name: DockerRunner

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  ACCESS_TOKEN: ${{secrets.github_token}}  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: vcolovic/github-runner:latest
          build-args: |
            TOKEN=${{ github.token }}
            REPO=format(https://github.com/{0},${{ github.repository }})
      
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3 
        with:
          token: ${{secrets.github_token}}  
          
      - name: Push image
        id: docker_push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: vcolovic/github-runner:${{ steps.buildnumber.outputs.build_number }},vcolovic/github-runner:latest
          build-args: |
            TOKEN=${{ github.token }}
            REPO=format(https://github.com/{0},${{ github.repository }})
  start_runner:
    needs: build-and-push
    runs-on: ubuntu-latest
    container:
      image: vcolovic/github-runner:latest
    steps:  
    - name: start container
      run: docker run vcolovic/github-runner:latest